services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: ${DOMAIN_NAME}
    env_file:
      - .env
    ports:
      - 25:25 # SMTP  (explicit TLS => STARTTLS)
      - 143:143 # IMAP4 (explicit TLS => STARTTLS)
      - 465:465 # ESMTP (implicit TLS)
      - 587:587 # ESMTP (explicit TLS => STARTTLS)
      - 993:993 # IMAP4 (implicit TLS)
    volumes:
      - ./src/data/dms/mail-data/:/var/mail/
      - ./src/data/dms/mail-state/:/var/mail-state/
      - ./src/data/dms/mail-logs/:/var/log/mail/
      - ./src/data/dms/config/:/tmp/docker-mailserver/
      - ./src/data/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1
      timeout: 3s
      retries: 0

    labels:
      - traefik.enable=true
      - traefik.tcp.routers.mail-smtp.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-smtp.entrypoints=smtp
      - traefik.tcp.routers.mail-smtp.service=smtp
      - traefik.tcp.services.mail-smtp.loadbalancer.server.port=25
      - traefik.tcp.services.mail-smtp.loadbalancer.proxyProtocol.version=2
      - traefik.tcp.routers.mail-submissions.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-submissions.entrypoints=smtp-submissions
      - traefik.tcp.routers.mail-submissions.service=smtp-submissions
      - traefik.tcp.services.mail-submissions.loadbalancer.server.port=465
      - traefik.tcp.services.mail-submissions.loadbalancer.proxyProtocol.version=2
      - traefik.tcp.routers.mail-submissions.rule=HostSNI(`${MAIL_HOST}`)
      - traefik.tcp.routers.mail-submissions.tls.passthrough=true
    networks:
      - traefik-network

  certbot:
    image: certbot/certbot:latest
    profiles:
      - certbot
    container_name: certbot
    hostname: certbot-server
    ports:
      - 80:80
    volumes:
      - ./src/data/letsencrypt:/etc/letsencrypt
      - ./src/data/certbot/logs:/var/log/letsencrypt/
    command:
      certonly --standalone --force-renewal --email ${TLS_MAILE} -d ${MAIL_HOST}
      --agree-tos
    networks:
      - traefik-network
networks:
  traefik-network:
    external: true
