services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: ${DOMAIN_NAME}
    env_file:
      - .env
    # ports:
    #   - 25:25 # SMTP  (explicit TLS => STARTTLS)
    #   - 143:143 # IMAP4 (explicit TLS => STARTTLS)
    #   - 465:465 # ESMTP (implicit TLS)
    #   - 587:587 # ESMTP (explicit TLS => STARTTLS)
    #   - 993:993 # IMAP4 (implicit TLS)

    labels:
      # SMTP
      - traefik.enable=true
      - traefik.tcp.routers.mail-smtp.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-smtp.entrypoints=mail-smtp
      - traefik.tcp.routers.mail-smtp.service=smtp
      - traefik.tcp.services.smtp.loadbalancer.server.port=25

      # SMTPS (Implicit TLS)
      - traefik.tcp.routers.mail-smtps.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-smtps.entrypoints=mail-submissions
      - traefik.tcp.routers.mail-smtps.tls=true
      - traefik.tcp.routers.mail-smtps.service=smtps
      - traefik.tcp.services.smtps.loadbalancer.server.port=465

      # Submission (Explicit TLS)
      - traefik.tcp.routers.mail-submission.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-submission.entrypoints=mail-submission
      - traefik.tcp.routers.mail-submission.service=submission
      - traefik.tcp.services.submission.loadbalancer.server.port=587

      # IMAP
      - traefik.tcp.routers.mail-imap.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-imap.entrypoints=mail-imap
      - traefik.tcp.routers.mail-imap.service=imap
      - traefik.tcp.services.imap.loadbalancer.server.port=143

      # IMAPS (Implicit TLS)
      - traefik.tcp.routers.mail-imaps.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-imaps.entrypoints=mail-imaps
      - traefik.tcp.routers.mail-imaps.tls=true
      - traefik.tcp.routers.mail-imaps.service=imaps
      - traefik.tcp.services.imaps.loadbalancer.server.port=993

      # POP3
      - traefik.tcp.routers.mail-pop3.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-pop3.entrypoints=mail-pop3
      - traefik.tcp.routers.mail-pop3.service=pop3
      - traefik.tcp.services.pop3.loadbalancer.server.port=110

      # POP3S (Implicit TLS)
      - traefik.tcp.routers.mail-pop3s.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-pop3s.entrypoints=mail-pop3s
      - traefik.tcp.routers.mail-pop3s.tls=true
      - traefik.tcp.routers.mail-pop3s.service=pop3s
      - traefik.tcp.services.pop3s.loadbalancer.server.port=995

      # ManageSieve
      - traefik.tcp.routers.mail-managesieve.rule=HostSNI(`*`)
      - traefik.tcp.routers.mail-managesieve.entrypoints=mail-managesieve
      - traefik.tcp.routers.mail-managesieve.service=managesieve
      - traefik.tcp.services.managesieve.loadbalancer.server.port=4190

    volumes:
      - ./src/data/dms/mail-data/:/var/mail/
      - ./src/data/dms/mail-state/:/var/mail-state/
      - ./src/data/dms/mail-logs/:/var/log/mail/
      - ./src/data/dms/config/:/tmp/docker-mailserver/
      - ./src/data/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1
      timeout: 3s
      retries: 0
    networks:
      - traefik-network

  certbot:
    image: certbot/certbot:latest
    profiles:
      - certbot
    container_name: certbot
    hostname: certbot-server
    ports:
      - 80:80
    volumes:
      - ./src/data/letsencrypt:/etc/letsencrypt
      - ./src/data/certbot/logs:/var/log/letsencrypt/
    command:
      certonly --standalone --force-renewal --email ${TLS_MAILE} -d ${MAIL_HOST}
      --agree-tos
    networks:
      - traefik-network
networks:
  traefik-network:
    external: true
